[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.34" # See latest release at: https://github.com/argotorg/solidity/releases

[fmt]
sort_imports = true
number_underscore = "thousands"

[profile.ci]
deny = "warnings" # Why not always: sometimes you just want to code and see what comes out
verbosity = 3 # Outputs stack traces for failed tests.
fuzz.seed = "0"
fuzz.runs = 10_000
